// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SnippetsColumns holds the columns for the "snippets" table.
	SnippetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "content", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SnippetsTable holds the schema information for the "snippets" table.
	SnippetsTable = &schema.Table{
		Name:       "snippets",
		Columns:    SnippetsColumns,
		PrimaryKey: []*schema.Column{SnippetsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SnippetsTable,
	}
)

func init() {
}
