// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nanaminakano/snippeter/ent/snippet"
)

// SnippetCreate is the builder for creating a Snippet entity.
type SnippetCreate struct {
	config
	mutation *SnippetMutation
	hooks    []Hook
}

// SetContent sets the "content" field.
func (sc *SnippetCreate) SetContent(s string) *SnippetCreate {
	sc.mutation.SetContent(s)
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *SnippetCreate) SetCreatedAt(t time.Time) *SnippetCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SnippetCreate) SetNillableCreatedAt(t *time.Time) *SnippetCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetID sets the "id" field.
func (sc *SnippetCreate) SetID(u uuid.UUID) *SnippetCreate {
	sc.mutation.SetID(u)
	return sc
}

// Mutation returns the SnippetMutation object of the builder.
func (sc *SnippetCreate) Mutation() *SnippetMutation {
	return sc.mutation
}

// Save creates the Snippet in the database.
func (sc *SnippetCreate) Save(ctx context.Context) (*Snippet, error) {
	sc.defaults()
	return withHooks[*Snippet, SnippetMutation](ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SnippetCreate) SaveX(ctx context.Context) *Snippet {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SnippetCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SnippetCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SnippetCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := snippet.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SnippetCreate) check() error {
	if _, ok := sc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Snippet.content"`)}
	}
	if v, ok := sc.mutation.Content(); ok {
		if err := snippet.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Snippet.content": %w`, err)}
		}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Snippet.created_at"`)}
	}
	return nil
}

func (sc *SnippetCreate) sqlSave(ctx context.Context) (*Snippet, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SnippetCreate) createSpec() (*Snippet, *sqlgraph.CreateSpec) {
	var (
		_node = &Snippet{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: snippet.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: snippet.FieldID,
			},
		}
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := sc.mutation.Content(); ok {
		_spec.SetField(snippet.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(snippet.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// SnippetCreateBulk is the builder for creating many Snippet entities in bulk.
type SnippetCreateBulk struct {
	config
	builders []*SnippetCreate
}

// Save creates the Snippet entities in the database.
func (scb *SnippetCreateBulk) Save(ctx context.Context) ([]*Snippet, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Snippet, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SnippetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SnippetCreateBulk) SaveX(ctx context.Context) []*Snippet {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SnippetCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SnippetCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
