// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nanaminakano/snippeter/ent/predicate"
	"github.com/nanaminakano/snippeter/ent/snippet"
)

// SnippetDelete is the builder for deleting a Snippet entity.
type SnippetDelete struct {
	config
	hooks    []Hook
	mutation *SnippetMutation
}

// Where appends a list predicates to the SnippetDelete builder.
func (sd *SnippetDelete) Where(ps ...predicate.Snippet) *SnippetDelete {
	sd.mutation.Where(ps...)
	return sd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sd *SnippetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, SnippetMutation](ctx, sd.sqlExec, sd.mutation, sd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sd *SnippetDelete) ExecX(ctx context.Context) int {
	n, err := sd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sd *SnippetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: snippet.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: snippet.FieldID,
			},
		},
	}
	if ps := sd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sd.mutation.done = true
	return affected, err
}

// SnippetDeleteOne is the builder for deleting a single Snippet entity.
type SnippetDeleteOne struct {
	sd *SnippetDelete
}

// Where appends a list predicates to the SnippetDelete builder.
func (sdo *SnippetDeleteOne) Where(ps ...predicate.Snippet) *SnippetDeleteOne {
	sdo.sd.mutation.Where(ps...)
	return sdo
}

// Exec executes the deletion query.
func (sdo *SnippetDeleteOne) Exec(ctx context.Context) error {
	n, err := sdo.sd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{snippet.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sdo *SnippetDeleteOne) ExecX(ctx context.Context) {
	if err := sdo.Exec(ctx); err != nil {
		panic(err)
	}
}
