// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nanaminakano/snippeter/ent/predicate"
	"github.com/nanaminakano/snippeter/ent/snippet"
)

// SnippetUpdate is the builder for updating Snippet entities.
type SnippetUpdate struct {
	config
	hooks    []Hook
	mutation *SnippetMutation
}

// Where appends a list predicates to the SnippetUpdate builder.
func (su *SnippetUpdate) Where(ps ...predicate.Snippet) *SnippetUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetLanguage sets the "language" field.
func (su *SnippetUpdate) SetLanguage(s string) *SnippetUpdate {
	su.mutation.SetLanguage(s)
	return su
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (su *SnippetUpdate) SetNillableLanguage(s *string) *SnippetUpdate {
	if s != nil {
		su.SetLanguage(*s)
	}
	return su
}

// SetContent sets the "content" field.
func (su *SnippetUpdate) SetContent(s string) *SnippetUpdate {
	su.mutation.SetContent(s)
	return su
}

// SetCreatedAt sets the "created_at" field.
func (su *SnippetUpdate) SetCreatedAt(t time.Time) *SnippetUpdate {
	su.mutation.SetCreatedAt(t)
	return su
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (su *SnippetUpdate) SetNillableCreatedAt(t *time.Time) *SnippetUpdate {
	if t != nil {
		su.SetCreatedAt(*t)
	}
	return su
}

// Mutation returns the SnippetMutation object of the builder.
func (su *SnippetUpdate) Mutation() *SnippetMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SnippetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, SnippetMutation](ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SnippetUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SnippetUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SnippetUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SnippetUpdate) check() error {
	if v, ok := su.mutation.Content(); ok {
		if err := snippet.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Snippet.content": %w`, err)}
		}
	}
	return nil
}

func (su *SnippetUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   snippet.Table,
			Columns: snippet.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: snippet.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Language(); ok {
		_spec.SetField(snippet.FieldLanguage, field.TypeString, value)
	}
	if value, ok := su.mutation.Content(); ok {
		_spec.SetField(snippet.FieldContent, field.TypeString, value)
	}
	if value, ok := su.mutation.CreatedAt(); ok {
		_spec.SetField(snippet.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{snippet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SnippetUpdateOne is the builder for updating a single Snippet entity.
type SnippetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SnippetMutation
}

// SetLanguage sets the "language" field.
func (suo *SnippetUpdateOne) SetLanguage(s string) *SnippetUpdateOne {
	suo.mutation.SetLanguage(s)
	return suo
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (suo *SnippetUpdateOne) SetNillableLanguage(s *string) *SnippetUpdateOne {
	if s != nil {
		suo.SetLanguage(*s)
	}
	return suo
}

// SetContent sets the "content" field.
func (suo *SnippetUpdateOne) SetContent(s string) *SnippetUpdateOne {
	suo.mutation.SetContent(s)
	return suo
}

// SetCreatedAt sets the "created_at" field.
func (suo *SnippetUpdateOne) SetCreatedAt(t time.Time) *SnippetUpdateOne {
	suo.mutation.SetCreatedAt(t)
	return suo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (suo *SnippetUpdateOne) SetNillableCreatedAt(t *time.Time) *SnippetUpdateOne {
	if t != nil {
		suo.SetCreatedAt(*t)
	}
	return suo
}

// Mutation returns the SnippetMutation object of the builder.
func (suo *SnippetUpdateOne) Mutation() *SnippetMutation {
	return suo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SnippetUpdateOne) Select(field string, fields ...string) *SnippetUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Snippet entity.
func (suo *SnippetUpdateOne) Save(ctx context.Context) (*Snippet, error) {
	return withHooks[*Snippet, SnippetMutation](ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SnippetUpdateOne) SaveX(ctx context.Context) *Snippet {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SnippetUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SnippetUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SnippetUpdateOne) check() error {
	if v, ok := suo.mutation.Content(); ok {
		if err := snippet.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Snippet.content": %w`, err)}
		}
	}
	return nil
}

func (suo *SnippetUpdateOne) sqlSave(ctx context.Context) (_node *Snippet, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   snippet.Table,
			Columns: snippet.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: snippet.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Snippet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, snippet.FieldID)
		for _, f := range fields {
			if !snippet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != snippet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Language(); ok {
		_spec.SetField(snippet.FieldLanguage, field.TypeString, value)
	}
	if value, ok := suo.mutation.Content(); ok {
		_spec.SetField(snippet.FieldContent, field.TypeString, value)
	}
	if value, ok := suo.mutation.CreatedAt(); ok {
		_spec.SetField(snippet.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Snippet{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{snippet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
